export const costHeading = {
  bathroom: "Bathroom Remodel Cost",
  kitchen: "Kitchen Remodel Cost",
  basement: "Cost to Finish a Basement",
  attic: "Cost to Finish Attic",
  cabinets: "Cost of Kitchen Cabinets",
  roofing: "Roof Replacement Cost",
  siding: "Siding Cost",
  deck: "Cost to Build a Deck",
  countertops: "Cost to Replace Kitchen Countertops​",
  masonry: "Masonry Work Cost",
  landscaping: "How Much Does Landscaping Cost",
  architecture: "Architect Cost",
  flooring: "Flooring Installation Cost",
  painting: "Cost To Paint a House",
  electrical: "Electrician Cost",
  plumbing: "Plumber Cost",
  doors: "Door Installation Cost",
  windows: "Window Replacement Cost",
  hvac: "HVAC Cost",
  excavation: "Excavation Cost",
  tile: "Tile Installation Cost",
};

export const locationNames = {
  seattle: "Seattle",
  oak_bay: "Oak Bay",
  saanich: "Saanich",
  sidney: "Sidney",
  colwood: "Colwood",
  metchosin: "Metchosin",
  north_saanich: "North Saanich",
  central_saanich: "Central Saanich",
  langford: "Langford",
  view_royal: "View Royal",
  duncan: "Duncan",
};
